#! /bin/sh

#Clean lingering programs when reloaded
"$HOME/.config/bspwm/clean" &

#Start polybar first
bash ~/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/background.jpg &

# Variable Defines
color0=#3B4252
color4=#D8DEE9

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

#Fix Mouse cursor on startup 
xsetroot -cursor_name left_ptr

#Set Keyboard Layout
setxkbmap -layout de 

#Monitor Config
bspc monitor -d 1 2 3 4

#BSPWM Config
bspc config border_width        2
bspc config top_padding         50
bspc config right_padding       9
bspc config left_padding        9
bspc config bottom_padding      9
bspc config window_gap          5 
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$color0"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          0.50
bspc config borderless_monocle   true  
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

#Auto-Start
bspc desktop -f ^9
sleep 0.50
urxvtc &
lxpolkit &
picom --config "$HOME/.config/bspwm/picom.conf" &
/usr/bin/synergys -f -d ERROR -n studio-pc -c /etc/synergy.conf -a 192.168.69.10:24800 --log ~/.local/log/synergy.log &
flameshot &
synergypid=0
while [ $synergypid -eq 0 ] 
do
   sleep 1
   synergypid=$(pidof synergy)
done
sleep 0.5
pingresult=$(ping -c 1 1.1.1.1 > /dev/null ; echo $?)
while [ $pingresult -ne 0 ]; do
  pingresult=$(ping -c 1 1.1.1.1 > /dev/null ; echo $?)
done
bspc desktop -f ^1
bash ~/Git

